# fly.toml app configuration file generated for llmcrawler on 2025-07-13T17:40:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'llmcrawler'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
